#spring
spring:
#mvc
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
    encoding: UTF-8
    content-type: text/html
    check-template: true
    mode: LEGACYHTML5
#kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: 0
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288

#server
server:
  port: 8081
  address:

logging:
  config: classpath:biased-logback.xml
  level:
        cn:
           edu:
              zzti:
                   bibased:
                            dao:
                               mapper: warn









