#spring
spring:
#mvc
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
    encoding: UTF-8
    content-type: text/html
    check-template: true
    mode: LEGACYHTML5

#server
server:
  port: 8081
  address:

logging:
  config: classpath:biased-logback.xml
  level:
        cn:
           edu:
              zzti:
                   bibased:
                            dao:
                               mapper: warn







